config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :weeks, :except =>[:index]
  end
  resources :weeks, :only => [] do
    resources :lessons, :except => [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :weeks
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :week
  validates :name, :presence => true
  validates :day, :presence => true
end

app/models/week.rb
class Week < ActiveRecord::Base
  has_many :lessons
  belongs_to :course
  validates :objective, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end
  def edit
    @course = Course.find(params[:id])
  end
  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end
private
  def course_params
    params.require(:course).permit(:name)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
    render :show
  end

  def show_previous
    @lesson = Lesson.finder(params[:id - 1])
    render :show
  end

  def new
    @week = Week.find(params[:week_id])
    @lesson = @week.lessons.new
  end

  def create
    @week = Week.find(params[:week_id])
    @lesson = @week.lessons.new(lesson_params)
    if @lesson.save
      redirect_to course_week_path(@week.course, @week)
    else
      render :new
    end
  end

  def edit
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
  end

  def update
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to week_lesson_path(@week, @lesson)
    else
      render :edit
    end
  end

  def destroy
    @week = Week.find(params[:week_id])
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to course_week_path(@week.course, @week)
  end

private
  def lesson_params
    params.require(:lesson).permit(:name, :day)
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  def show
    @course = Course.find(params[:course_id])
    @week = Week.find(params[:id])
  end

  def new
    @course = Course.find(params[:course_id])
    @week = @course.weeks.new
  end

  def create
    @course = Course.find(params[:course_id])
    @week = @course.weeks.new(week_params)
    if @week.save
      redirect_to course_path(@week.course)
    else
      render :new
    end
  end

  def edit
    @course = Course.find(params[:course_id])
    @week = Week.find(params[:id])
  end

  def update
    @course = Course.find(params[:course_id])
    @week = Week.find(params[:id])
    if @week.update(week_params)
      redirect_to course_path(@week.course)
    else
      render :edit
    end
  end

  def destroy
    @week = Week.find(params[:id])
    @week.destroy
    redirect_to course_path(@week.course)
  end

private
  def week_params
    params.require(:week).permit(:objective, :week_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/courses/_form.html.erb
<%=render "layouts/errors", :object => @course %>


<%= form_for @course do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/courses/edit.html.erb
<h4>Edit Course:</h4>

<%= render "form" %>

app/views/courses/index.html.erb
<h1 class="header">Courses</h1>

<% if @courses.any? %>

    <% @courses.each do |course| %>
      <h4 class="courses"><%= link_to course.name, course_path(course) %></h4>
      <% end %>

<% else %>
  <h4>There are no courses available yet</h4>
<% end %>
<h4 class="button-add"><%= link_to "Add Course", new_course_path %></h4>

app/views/courses/new.html.erb
<h4>Add a Course:</h4>

<%= render 'form' %>

app/views/courses/show.html.erb
<h1 class="header"><%= @course.name %></h1>


<% if @course.weeks.any? %>
    <% @course.weeks.each do |week| %>
      <h4 class="courses">(Week <%= week.week_number %>) <%= link_to week.objective, course_week_path(week.course, week) %></h4>
    <% end %>
<% else %>
  <h4 >Write some weeks!</h4>
<% end %>

<h4 class="button button-add"><%= link_to "Add Week", new_course_week_path(@course) %></h4>
<h4 class="button" ><%= link_to "Edit Course", edit_course_path(@course) %></h4>
<h4 class="button"><%= link_to "Delete Course", course_path(@course), :data => {:confirm => "Are you sure?", :method => "delete"}%></h4>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnHowToProgram</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Courses", courses_path%></li>
        <li><%=yield(:previous) %></li>
        <li><%= yield(:next)%></li>
      </ul>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-search"></span></button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for [@week, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name%>
  <%= f.label :day%>
  <%= f.text_field :day%>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h3>Edit Lesson</h3>

<%= render "form" %>

app/views/lessons/new.html.erb
<%= render 'form' %>

app/views/lessons/show.html.erb
<% content_for(:previous, (link_to "Previous", week_lesson_path()))%>
<% content_for(:next, (link_to "Next", week_lesson_path()))%>

<h2> <%= @lesson.name %> </h2>

<%= link_to "Edit Lesson", edit_week_lesson_path(@lesson.week, @lesson) %>
<%= link_to "Delete Lesson", week_lesson_path(@lesson.week, @lesson),
      :data => {:confirm => "Really?", :method => "delete"} %>

app/views/weeks/_form.html.erb
<%= render "layouts/errors", :object => @week %>

<%= form_for [@course, @week] do |f| %>
  <%= f.label :objective %>
  <%= f.text_field :objective%>
  <%= f.label :week_number%>
  <%= f.text_field :week_number%>
  <%= f.submit %>
<% end %>

app/views/weeks/edit.html.erb
<h3>Edit Week</h3>

<%= render "form" %>

app/views/weeks/new.html.erb
Add Week

<%= render 'form' %>

app/views/weeks/show.html.erb
<h2> <%= @week.objective %> </h2>

<% if @week.lessons.any? %>
    <% @week.lessons.each do |lesson| %>
      <h4 class="weeks"><%= lesson.day %> <%= link_to lesson.name, week_lesson_path(lesson.week, lesson) %></h4>
    <% end %>
<% else %>
  <h4 >Write some lessons!</h4>
<% end %>

<%= link_to "Add Lesson", new_week_lesson_path(@week) %>
<%= link_to "Edit Week", edit_course_week_path(@week.course, @week)%> | <%= link_to "Delete Week", course_week_path(@week.course, @week),
      :data => {:confirm => "Really?", :method => "delete"} %>